#  - repo: https://github.com/psf/black
#    rev: 22.3.0
#    hooks:
#      - id: black
#        language_version: python3.8
#
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.910
#    hooks:
#      - id: mypy
#        additional_dependencies: [types-requests, types-PyYAML]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace


  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
