#  - repo: https://github.com/psf/black
#    rev: 22.3.0
#    hooks:
#      - id: black
#        language_version: python3.8
#
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.910
#    hooks:
#      - id: mypy
#        additional_dependencies: [types-requests, types-PyYAML]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: rustfmt
        language: system
        types: [rust]
        pass_filenames: false
