# Generated by Django 4.2.3 on 2023-07-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('gurus', models.ManyToManyField(blank=True, related_name='guru_links', to='guru_app.guru')),
                ('tags', models.ManyToManyField(blank=True, related_name='link_tags', to='guru_app.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('url', models.URLField()),
                ('notes', models.TextField()),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('gurus', models.ManyToManyField(blank=True, related_name='guru_episodes', to='guru_app.guru')),
                ('links', models.ManyToManyField(to='guru_app.link')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
